kind: Service # Service externo, para admin y api
apiVersion: v1
metadata:
  name: bondy-export
  namespace: magenta
  labels:
    app: bondy
    tier: gateway
spec:
  ports:
    - name: api
      port: 8080
      targetPort: 18080
      #nodePort: 32500
    - name: admin
      port: 8081
      targetPort: 18081
      #nodePort: 32501
  #type: NodePort
  type: LoadBalancer
  selector:
    app: bondy
