kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    app: bondy
    tier: gateway
  name: bondy-claim
  namespace: magenta
  annotations:
    volume.beta.kubernetes.io/storage-class: fast
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # selector:
  #   matchLabels:
  #     app: "bondy"
